;Class:CSE 313 Machine Organization Lab
;Intstructor Taline Georgiou
;Term: Spring 2016
;Names
;Lab#3 "Days of the week" INPUT and OUTPUT
;THIS PROGRAM IS USED TO DISPLAY THE DAYS OF THE WEEK.
;IT TAKES THE USERS INPUT OF A NUMBER (0-6) AND WILL DISPLAY THE GIVEN DAY OF THE WEEK BASED ON THE USERS INPUT.
;IF THE NUMBER IS INVALID THE PROGRAM WILL COME TO HALT.	

	.ORIG X3000
RESTART	LEA R0, PROMPT
	PUTS
	GETC
	ADD R3, R0, X0		;COPY R0 INTO R3
	ADD R3, R3, #-16	;SUBTRACT 48, ACII VALUE OF 0
	ADD R3, R3, #-16
	ADD R3, R3, #-16	;R3 NOW CONTAINS VALUE
	ADD R4, R3, #-6		;CHECKS FOR VALID NUMBER
	BRp BREAK		;BREAKS FOR HALT
	LEA R0, DAYS
	ADD R3, R3, X0
LOOP	BRz DISPLAY
	ADD R0, R0, #10
	ADD R3, R3, #-1
	BR LOOP
	DISPLAY PUTS
	LEA R0, LF
	PUTS

	BR RESTART
	



BREAK 	HALT
PROMPT	.STRINGZ "Please enter a Number: "
DAYS   	.STRINGZ "SUNDAY   "
	.STRINGZ "MONDAY   "
	.STRINGZ "TUESDAY  "
	.STRINGZ "WEDNESDAY"
	.STRINGZ "THURSDAY "
	.STRINGZ "FRIDAY   "
	.STRINGZ "SATURDAY "
LF	.FILL X000A

.END